/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'isDraft' : boolean,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface BlogPostInput {
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'isDraft' : boolean,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmissionInput {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'courseInterested' : string,
}
export interface ContactSubmissionPublic {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
  'courseInterested' : string,
}
export interface Course {
  'id' : bigint,
  'careerProspects' : Array<string>,
  'partnerCollegesCount' : bigint,
  'stream' : CourseStream,
  'duration' : string,
  'name' : string,
  'description' : string,
  'feesINR' : bigint,
  'isActive' : boolean,
  'level' : CourseLevel,
  'eligibility' : string,
  'courseType' : CourseType,
}
export interface CourseInput {
  'careerProspects' : Array<string>,
  'partnerCollegesCount' : bigint,
  'stream' : CourseStream,
  'duration' : string,
  'name' : string,
  'description' : string,
  'feesINR' : bigint,
  'isActive' : boolean,
  'level' : CourseLevel,
  'eligibility' : string,
  'courseType' : CourseType,
}
export type CourseLevel = { 'PhD' : null } |
  { 'Bachelor' : null } |
  { 'Diploma' : null } |
  { 'Master' : null };
export type CourseStream = { 'Law' : null } |
  { 'Arts' : null } |
  { 'Engineering' : null } |
  { 'Commerce' : null } |
  { 'Management' : null } |
  { 'Medical' : null } |
  { 'Science' : null } |
  { 'Other' : null };
export type CourseType = { 'PartTime' : null } |
  { 'FullTime' : null };
export interface Testimonial {
  'id' : bigint,
  'starRating' : bigint,
  'studentName' : string,
  'quote' : string,
  'achievement' : string,
  'isActive' : boolean,
  'courseStream' : string,
  'isFeatured' : boolean,
}
export interface TestimonialInput {
  'starRating' : bigint,
  'studentName' : string,
  'quote' : string,
  'achievement' : string,
  'isActive' : boolean,
  'courseStream' : string,
  'isFeatured' : boolean,
}
export interface _SERVICE {
  'adminCreateBlogPost' : ActorMethod<[string, BlogPostInput], bigint>,
  'adminCreateCourse' : ActorMethod<[string, CourseInput], bigint>,
  'adminCreateTestimonial' : ActorMethod<[string, TestimonialInput], bigint>,
  'adminDeleteBlogPost' : ActorMethod<[string, bigint], boolean>,
  'adminDeleteCourse' : ActorMethod<[string, bigint], boolean>,
  'adminDeleteTestimonial' : ActorMethod<[string, bigint], boolean>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'adminSeedSampleData' : ActorMethod<[string], string>,
  'adminUpdateBlogPost' : ActorMethod<[string, bigint, BlogPostInput], boolean>,
  'adminUpdateCourse' : ActorMethod<[string, bigint, CourseInput], boolean>,
  'adminUpdateTestimonial' : ActorMethod<
    [string, bigint, TestimonialInput],
    boolean
  >,
  'deleteContactSubmission' : ActorMethod<[string, bigint], boolean>,
  'getBlogPostById' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[boolean], Array<BlogPost>>,
  'getContactSubmissions' : ActorMethod<
    [string],
    Array<ContactSubmissionPublic>
  >,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getCourses' : ActorMethod<[boolean], Array<Course>>,
  'getTestimonialById' : ActorMethod<[bigint], [] | [Testimonial]>,
  'getTestimonials' : ActorMethod<[boolean, boolean], Array<Testimonial>>,
  'markContactSubmissionRead' : ActorMethod<[string, bigint], boolean>,
  'submitContactForm' : ActorMethod<[ContactSubmissionInput], bigint>,
  'validateAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];