/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'isDraft' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const CourseStream = IDL.Variant({
  'Law' : IDL.Null,
  'Arts' : IDL.Null,
  'Engineering' : IDL.Null,
  'Commerce' : IDL.Null,
  'Management' : IDL.Null,
  'Medical' : IDL.Null,
  'Science' : IDL.Null,
  'Other' : IDL.Null,
});
export const CourseLevel = IDL.Variant({
  'PhD' : IDL.Null,
  'Bachelor' : IDL.Null,
  'Diploma' : IDL.Null,
  'Master' : IDL.Null,
});
export const CourseType = IDL.Variant({
  'PartTime' : IDL.Null,
  'FullTime' : IDL.Null,
});
export const CourseInput = IDL.Record({
  'careerProspects' : IDL.Vec(IDL.Text),
  'partnerCollegesCount' : IDL.Nat,
  'stream' : CourseStream,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'feesINR' : IDL.Nat,
  'isActive' : IDL.Bool,
  'level' : CourseLevel,
  'eligibility' : IDL.Text,
  'courseType' : CourseType,
});
export const TestimonialInput = IDL.Record({
  'starRating' : IDL.Nat,
  'studentName' : IDL.Text,
  'quote' : IDL.Text,
  'achievement' : IDL.Text,
  'isActive' : IDL.Bool,
  'courseStream' : IDL.Text,
  'isFeatured' : IDL.Bool,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'isDraft' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ContactSubmissionPublic = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'courseInterested' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'careerProspects' : IDL.Vec(IDL.Text),
  'partnerCollegesCount' : IDL.Nat,
  'stream' : CourseStream,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'feesINR' : IDL.Nat,
  'isActive' : IDL.Bool,
  'level' : CourseLevel,
  'eligibility' : IDL.Text,
  'courseType' : CourseType,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'starRating' : IDL.Nat,
  'studentName' : IDL.Text,
  'quote' : IDL.Text,
  'achievement' : IDL.Text,
  'isActive' : IDL.Bool,
  'courseStream' : IDL.Text,
  'isFeatured' : IDL.Bool,
});
export const ContactSubmissionInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'courseInterested' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminCreateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [IDL.Nat], []),
  'adminCreateCourse' : IDL.Func([IDL.Text, CourseInput], [IDL.Nat], []),
  'adminCreateTestimonial' : IDL.Func(
      [IDL.Text, TestimonialInput],
      [IDL.Nat],
      [],
    ),
  'adminDeleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'adminDeleteCourse' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'adminDeleteTestimonial' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'adminSeedSampleData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'adminUpdateBlogPost' : IDL.Func(
      [IDL.Text, IDL.Nat, BlogPostInput],
      [IDL.Bool],
      [],
    ),
  'adminUpdateCourse' : IDL.Func(
      [IDL.Text, IDL.Nat, CourseInput],
      [IDL.Bool],
      [],
    ),
  'adminUpdateTestimonial' : IDL.Func(
      [IDL.Text, IDL.Nat, TestimonialInput],
      [IDL.Bool],
      [],
    ),
  'deleteContactSubmission' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getBlogPostById' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([IDL.Bool], [IDL.Vec(BlogPost)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmissionPublic)],
      ['query'],
    ),
  'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourses' : IDL.Func([IDL.Bool], [IDL.Vec(Course)], ['query']),
  'getTestimonialById' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
  'getTestimonials' : IDL.Func(
      [IDL.Bool, IDL.Bool],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'markContactSubmissionRead' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'submitContactForm' : IDL.Func([ContactSubmissionInput], [IDL.Nat], []),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'isDraft' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const CourseStream = IDL.Variant({
    'Law' : IDL.Null,
    'Arts' : IDL.Null,
    'Engineering' : IDL.Null,
    'Commerce' : IDL.Null,
    'Management' : IDL.Null,
    'Medical' : IDL.Null,
    'Science' : IDL.Null,
    'Other' : IDL.Null,
  });
  const CourseLevel = IDL.Variant({
    'PhD' : IDL.Null,
    'Bachelor' : IDL.Null,
    'Diploma' : IDL.Null,
    'Master' : IDL.Null,
  });
  const CourseType = IDL.Variant({
    'PartTime' : IDL.Null,
    'FullTime' : IDL.Null,
  });
  const CourseInput = IDL.Record({
    'careerProspects' : IDL.Vec(IDL.Text),
    'partnerCollegesCount' : IDL.Nat,
    'stream' : CourseStream,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'feesINR' : IDL.Nat,
    'isActive' : IDL.Bool,
    'level' : CourseLevel,
    'eligibility' : IDL.Text,
    'courseType' : CourseType,
  });
  const TestimonialInput = IDL.Record({
    'starRating' : IDL.Nat,
    'studentName' : IDL.Text,
    'quote' : IDL.Text,
    'achievement' : IDL.Text,
    'isActive' : IDL.Bool,
    'courseStream' : IDL.Text,
    'isFeatured' : IDL.Bool,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'isDraft' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ContactSubmissionPublic = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'courseInterested' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'careerProspects' : IDL.Vec(IDL.Text),
    'partnerCollegesCount' : IDL.Nat,
    'stream' : CourseStream,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'feesINR' : IDL.Nat,
    'isActive' : IDL.Bool,
    'level' : CourseLevel,
    'eligibility' : IDL.Text,
    'courseType' : CourseType,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'starRating' : IDL.Nat,
    'studentName' : IDL.Text,
    'quote' : IDL.Text,
    'achievement' : IDL.Text,
    'isActive' : IDL.Bool,
    'courseStream' : IDL.Text,
    'isFeatured' : IDL.Bool,
  });
  const ContactSubmissionInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'courseInterested' : IDL.Text,
  });
  
  return IDL.Service({
    'adminCreateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [IDL.Nat], []),
    'adminCreateCourse' : IDL.Func([IDL.Text, CourseInput], [IDL.Nat], []),
    'adminCreateTestimonial' : IDL.Func(
        [IDL.Text, TestimonialInput],
        [IDL.Nat],
        [],
      ),
    'adminDeleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'adminDeleteCourse' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'adminDeleteTestimonial' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'adminSeedSampleData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'adminUpdateBlogPost' : IDL.Func(
        [IDL.Text, IDL.Nat, BlogPostInput],
        [IDL.Bool],
        [],
      ),
    'adminUpdateCourse' : IDL.Func(
        [IDL.Text, IDL.Nat, CourseInput],
        [IDL.Bool],
        [],
      ),
    'adminUpdateTestimonial' : IDL.Func(
        [IDL.Text, IDL.Nat, TestimonialInput],
        [IDL.Bool],
        [],
      ),
    'deleteContactSubmission' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getBlogPostById' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([IDL.Bool], [IDL.Vec(BlogPost)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmissionPublic)],
        ['query'],
      ),
    'getCourseById' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourses' : IDL.Func([IDL.Bool], [IDL.Vec(Course)], ['query']),
    'getTestimonialById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Testimonial)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func(
        [IDL.Bool, IDL.Bool],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'markContactSubmissionRead' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'submitContactForm' : IDL.Func([ContactSubmissionInput], [IDL.Nat], []),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };