/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CourseInput {
    careerProspects: Array<string>;
    partnerCollegesCount: bigint;
    stream: CourseStream;
    duration: string;
    name: string;
    description: string;
    feesINR: bigint;
    isActive: boolean;
    level: CourseLevel;
    eligibility: string;
    courseType: CourseType;
}
export interface Course {
    id: bigint;
    careerProspects: Array<string>;
    partnerCollegesCount: bigint;
    stream: CourseStream;
    duration: string;
    name: string;
    description: string;
    feesINR: bigint;
    isActive: boolean;
    level: CourseLevel;
    eligibility: string;
    courseType: CourseType;
}
export interface Testimonial {
    id: bigint;
    starRating: bigint;
    studentName: string;
    quote: string;
    achievement: string;
    isActive: boolean;
    courseStream: string;
    isFeatured: boolean;
}
export interface ContactSubmissionPublic {
    id: bigint;
    name: string;
    submittedAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
    phone: string;
    courseInterested: string;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    publishDate: bigint;
    slug: string;
    tags: Array<string>;
    author: string;
    isDraft: boolean;
    imageUrl: string;
    excerpt: string;
    category: string;
}
export interface BlogPostInput {
    title: string;
    content: string;
    publishDate: bigint;
    slug: string;
    tags: Array<string>;
    author: string;
    isDraft: boolean;
    imageUrl: string;
    excerpt: string;
    category: string;
}
export interface TestimonialInput {
    starRating: bigint;
    studentName: string;
    quote: string;
    achievement: string;
    isActive: boolean;
    courseStream: string;
    isFeatured: boolean;
}
export interface ContactSubmissionInput {
    name: string;
    email: string;
    message: string;
    phone: string;
    courseInterested: string;
}
export enum CourseLevel {
    PhD = "PhD",
    Bachelor = "Bachelor",
    Diploma = "Diploma",
    Master = "Master"
}
export enum CourseStream {
    Law = "Law",
    Arts = "Arts",
    Engineering = "Engineering",
    Commerce = "Commerce",
    Management = "Management",
    Medical = "Medical",
    Science = "Science",
    Other = "Other"
}
export enum CourseType {
    PartTime = "PartTime",
    FullTime = "FullTime"
}
export interface backendInterface {
    adminCreateBlogPost(token: string, input: BlogPostInput): Promise<bigint>;
    adminCreateCourse(token: string, input: CourseInput): Promise<bigint>;
    adminCreateTestimonial(token: string, input: TestimonialInput): Promise<bigint>;
    adminDeleteBlogPost(token: string, id: bigint): Promise<boolean>;
    adminDeleteCourse(token: string, id: bigint): Promise<boolean>;
    adminDeleteTestimonial(token: string, id: bigint): Promise<boolean>;
    adminLogin(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogout(token: string): Promise<void>;
    adminSeedSampleData(token: string): Promise<string>;
    adminUpdateBlogPost(token: string, id: bigint, input: BlogPostInput): Promise<boolean>;
    adminUpdateCourse(token: string, id: bigint, input: CourseInput): Promise<boolean>;
    adminUpdateTestimonial(token: string, id: bigint, input: TestimonialInput): Promise<boolean>;
    deleteContactSubmission(token: string, id: bigint): Promise<boolean>;
    getBlogPostById(id: bigint): Promise<BlogPost | null>;
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getBlogPosts(publishedOnly: boolean): Promise<Array<BlogPost>>;
    getContactSubmissions(token: string): Promise<Array<ContactSubmissionPublic>>;
    getCourseById(id: bigint): Promise<Course | null>;
    getCourses(activeOnly: boolean): Promise<Array<Course>>;
    getTestimonialById(id: bigint): Promise<Testimonial | null>;
    getTestimonials(activeOnly: boolean, featuredOnly: boolean): Promise<Array<Testimonial>>;
    markContactSubmissionRead(token: string, id: bigint): Promise<boolean>;
    submitContactForm(input: ContactSubmissionInput): Promise<bigint>;
    validateAdminSession(token: string): Promise<boolean>;
}
import type { BlogPost as _BlogPost, Course as _Course, CourseInput as _CourseInput, CourseLevel as _CourseLevel, CourseStream as _CourseStream, CourseType as _CourseType, Testimonial as _Testimonial } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminCreateBlogPost(arg0: string, arg1: BlogPostInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateBlogPost(arg0, arg1);
            return result;
        }
    }
    async adminCreateCourse(arg0: string, arg1: CourseInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateCourse(arg0, to_candid_CourseInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateCourse(arg0, to_candid_CourseInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminCreateTestimonial(arg0: string, arg1: TestimonialInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTestimonial(arg0, arg1);
            return result;
        }
    }
    async adminDeleteBlogPost(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteBlogPost(arg0, arg1);
            return result;
        }
    }
    async adminDeleteCourse(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCourse(arg0, arg1);
            return result;
        }
    }
    async adminDeleteTestimonial(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteTestimonial(arg0, arg1);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async adminSeedSampleData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSeedSampleData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSeedSampleData(arg0);
            return result;
        }
    }
    async adminUpdateBlogPost(arg0: string, arg1: bigint, arg2: BlogPostInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateBlogPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateBlogPost(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUpdateCourse(arg0: string, arg1: bigint, arg2: CourseInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCourse(arg0, arg1, to_candid_CourseInput_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCourse(arg0, arg1, to_candid_CourseInput_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminUpdateTestimonial(arg0: string, arg1: bigint, arg2: TestimonialInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTestimonial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTestimonial(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteContactSubmission(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactSubmission(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactSubmission(arg0, arg1);
            return result;
        }
    }
    async getBlogPostById(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(arg0: boolean): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts(arg0);
            return result;
        }
    }
    async getContactSubmissions(arg0: string): Promise<Array<ContactSubmissionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions(arg0);
            return result;
        }
    }
    async getCourseById(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourses(arg0: boolean): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialById(arg0: bigint): Promise<Testimonial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(arg0: boolean, arg1: boolean): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials(arg0, arg1);
            return result;
        }
    }
    async markContactSubmissionRead(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactSubmissionRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactSubmissionRead(arg0, arg1);
            return result;
        }
    }
    async submitContactForm(arg0: ContactSubmissionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async validateAdminSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
}
function from_candid_CourseLevel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseLevel): CourseLevel {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_CourseStream_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseStream): CourseStream {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CourseType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseType): CourseType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Testimonial]): Testimonial | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    careerProspects: Array<string>;
    partnerCollegesCount: bigint;
    stream: _CourseStream;
    duration: string;
    name: string;
    description: string;
    feesINR: bigint;
    isActive: boolean;
    level: _CourseLevel;
    eligibility: string;
    courseType: _CourseType;
}): {
    id: bigint;
    careerProspects: Array<string>;
    partnerCollegesCount: bigint;
    stream: CourseStream;
    duration: string;
    name: string;
    description: string;
    feesINR: bigint;
    isActive: boolean;
    level: CourseLevel;
    eligibility: string;
    courseType: CourseType;
} {
    return {
        id: value.id,
        careerProspects: value.careerProspects,
        partnerCollegesCount: value.partnerCollegesCount,
        stream: from_candid_CourseStream_n14(_uploadFile, _downloadFile, value.stream),
        duration: value.duration,
        name: value.name,
        description: value.description,
        feesINR: value.feesINR,
        isActive: value.isActive,
        level: from_candid_CourseLevel_n16(_uploadFile, _downloadFile, value.level),
        eligibility: value.eligibility,
        courseType: from_candid_CourseType_n18(_uploadFile, _downloadFile, value.courseType)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Law: null;
} | {
    Arts: null;
} | {
    Engineering: null;
} | {
    Commerce: null;
} | {
    Management: null;
} | {
    Medical: null;
} | {
    Science: null;
} | {
    Other: null;
}): CourseStream {
    return "Law" in value ? CourseStream.Law : "Arts" in value ? CourseStream.Arts : "Engineering" in value ? CourseStream.Engineering : "Commerce" in value ? CourseStream.Commerce : "Management" in value ? CourseStream.Management : "Medical" in value ? CourseStream.Medical : "Science" in value ? CourseStream.Science : "Other" in value ? CourseStream.Other : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PhD: null;
} | {
    Bachelor: null;
} | {
    Diploma: null;
} | {
    Master: null;
}): CourseLevel {
    return "PhD" in value ? CourseLevel.PhD : "Bachelor" in value ? CourseLevel.Bachelor : "Diploma" in value ? CourseLevel.Diploma : "Master" in value ? CourseLevel.Master : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PartTime: null;
} | {
    FullTime: null;
}): CourseType {
    return "PartTime" in value ? CourseType.PartTime : "FullTime" in value ? CourseType.FullTime : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n12(_uploadFile, _downloadFile, x));
}
function to_candid_CourseInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseInput): _CourseInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CourseLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseLevel): _CourseLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CourseStream_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseStream): _CourseStream {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CourseType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseType): _CourseType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    careerProspects: Array<string>;
    partnerCollegesCount: bigint;
    stream: CourseStream;
    duration: string;
    name: string;
    description: string;
    feesINR: bigint;
    isActive: boolean;
    level: CourseLevel;
    eligibility: string;
    courseType: CourseType;
}): {
    careerProspects: Array<string>;
    partnerCollegesCount: bigint;
    stream: _CourseStream;
    duration: string;
    name: string;
    description: string;
    feesINR: bigint;
    isActive: boolean;
    level: _CourseLevel;
    eligibility: string;
    courseType: _CourseType;
} {
    return {
        careerProspects: value.careerProspects,
        partnerCollegesCount: value.partnerCollegesCount,
        stream: to_candid_CourseStream_n3(_uploadFile, _downloadFile, value.stream),
        duration: value.duration,
        name: value.name,
        description: value.description,
        feesINR: value.feesINR,
        isActive: value.isActive,
        level: to_candid_CourseLevel_n5(_uploadFile, _downloadFile, value.level),
        eligibility: value.eligibility,
        courseType: to_candid_CourseType_n7(_uploadFile, _downloadFile, value.courseType)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseStream): {
    Law: null;
} | {
    Arts: null;
} | {
    Engineering: null;
} | {
    Commerce: null;
} | {
    Management: null;
} | {
    Medical: null;
} | {
    Science: null;
} | {
    Other: null;
} {
    return value == CourseStream.Law ? {
        Law: null
    } : value == CourseStream.Arts ? {
        Arts: null
    } : value == CourseStream.Engineering ? {
        Engineering: null
    } : value == CourseStream.Commerce ? {
        Commerce: null
    } : value == CourseStream.Management ? {
        Management: null
    } : value == CourseStream.Medical ? {
        Medical: null
    } : value == CourseStream.Science ? {
        Science: null
    } : value == CourseStream.Other ? {
        Other: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseLevel): {
    PhD: null;
} | {
    Bachelor: null;
} | {
    Diploma: null;
} | {
    Master: null;
} {
    return value == CourseLevel.PhD ? {
        PhD: null
    } : value == CourseLevel.Bachelor ? {
        Bachelor: null
    } : value == CourseLevel.Diploma ? {
        Diploma: null
    } : value == CourseLevel.Master ? {
        Master: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseType): {
    PartTime: null;
} | {
    FullTime: null;
} {
    return value == CourseType.PartTime ? {
        PartTime: null
    } : value == CourseType.FullTime ? {
        FullTime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
